<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSLYEIRy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSLYEIRy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSLYEIRy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSLYEIRy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSLYEIRy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SLYEIRy',
    'container.build_id' => '0157400c',
    'container.build_time' => 1609339946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSLYEIRy');
